require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ResistanceMembersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ResistanceMember. As you add validations to ResistanceMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResistanceMembersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all resistance_members as @resistance_members" do
      resistance_member = ResistanceMember.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:resistance_members)).to eq([resistance_member])
    end
  end

  describe "GET show" do
    it "assigns the requested resistance_member as @resistance_member" do
      resistance_member = ResistanceMember.create! valid_attributes
      get :show, {:id => resistance_member.to_param}, valid_session
      expect(assigns(:resistance_member)).to eq(resistance_member)
    end
  end

  describe "GET new" do
    it "assigns a new resistance_member as @resistance_member" do
      get :new, {}, valid_session
      expect(assigns(:resistance_member)).to be_a_new(ResistanceMember)
    end
  end

  describe "GET edit" do
    it "assigns the requested resistance_member as @resistance_member" do
      resistance_member = ResistanceMember.create! valid_attributes
      get :edit, {:id => resistance_member.to_param}, valid_session
      expect(assigns(:resistance_member)).to eq(resistance_member)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ResistanceMember" do
        expect {
          post :create, {:resistance_member => valid_attributes}, valid_session
        }.to change(ResistanceMember, :count).by(1)
      end

      it "assigns a newly created resistance_member as @resistance_member" do
        post :create, {:resistance_member => valid_attributes}, valid_session
        expect(assigns(:resistance_member)).to be_a(ResistanceMember)
        expect(assigns(:resistance_member)).to be_persisted
      end

      it "redirects to the created resistance_member" do
        post :create, {:resistance_member => valid_attributes}, valid_session
        expect(response).to redirect_to(ResistanceMember.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved resistance_member as @resistance_member" do
        post :create, {:resistance_member => invalid_attributes}, valid_session
        expect(assigns(:resistance_member)).to be_a_new(ResistanceMember)
      end

      it "re-renders the 'new' template" do
        post :create, {:resistance_member => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested resistance_member" do
        resistance_member = ResistanceMember.create! valid_attributes
        put :update, {:id => resistance_member.to_param, :resistance_member => new_attributes}, valid_session
        resistance_member.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested resistance_member as @resistance_member" do
        resistance_member = ResistanceMember.create! valid_attributes
        put :update, {:id => resistance_member.to_param, :resistance_member => valid_attributes}, valid_session
        expect(assigns(:resistance_member)).to eq(resistance_member)
      end

      it "redirects to the resistance_member" do
        resistance_member = ResistanceMember.create! valid_attributes
        put :update, {:id => resistance_member.to_param, :resistance_member => valid_attributes}, valid_session
        expect(response).to redirect_to(resistance_member)
      end
    end

    describe "with invalid params" do
      it "assigns the resistance_member as @resistance_member" do
        resistance_member = ResistanceMember.create! valid_attributes
        put :update, {:id => resistance_member.to_param, :resistance_member => invalid_attributes}, valid_session
        expect(assigns(:resistance_member)).to eq(resistance_member)
      end

      it "re-renders the 'edit' template" do
        resistance_member = ResistanceMember.create! valid_attributes
        put :update, {:id => resistance_member.to_param, :resistance_member => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested resistance_member" do
      resistance_member = ResistanceMember.create! valid_attributes
      expect {
        delete :destroy, {:id => resistance_member.to_param}, valid_session
      }.to change(ResistanceMember, :count).by(-1)
    end

    it "redirects to the resistance_members list" do
      resistance_member = ResistanceMember.create! valid_attributes
      delete :destroy, {:id => resistance_member.to_param}, valid_session
      expect(response).to redirect_to(resistance_members_url)
    end
  end

end
